language: kotlin

notifications:
  email:
    recipients:
      - roland@tritsch.org
    on_success: always
    on_failure: always

before_install:
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - sdk version
  - sdk install gradle 4.9
  - gradle --version

script:
  - travis_wait 60 gradle test
  - travis_wait 60 gradle run
